### ISSUE TITLE
多重布局的问题

### ISSUE THREAD

**Issue by white37** [Dev-Wiki/RecyclerView#1]
你这样封装多个Item的ViewHolder的时候会有一个问题，就是两种不同类型的没有重合的部分，单独生成不同的ViewHolder,但是因为你封装的adapter里面使用了泛型，必须传递一个ViewHolder过去，那我应该传递哪一个ViewHolder过去呢，你的解决办法是两个ViewHolder之间存在继承关系才解决，如果他们之间没有继承关系呢。你如何解决这种

**Comment by Dev-Wiki** [comment]
抱歉，才看到你的消息。

多种布局没有重合的话，Adapter可以传递BaseHolder。
为了验证你的需求，我专门添加了Sample。详细请参见Sample中的[MultiActivity](https://github.com/Dev-Wiki/RecyclerView/tree/master/app/src/main/java/net/devwiki/recyclerview/multi)

**Comment by Dev-Wiki** [comment]
抱歉，才看到你的消息。

多种布局没有重合的话，Adapter可以传递BaseHolder。
为了验证你的需求，我专门添加了Sample。详细请参见Sample中的[MultiActivity](https://github.com/Dev-Wiki/RecyclerView/tree/master/app/src/main/java/net/devwiki/recyclerview/multi)
